### ISSUE TITLE
Reader do not detect that the database has been partially updated

### ISSUE THREAD

**Issue by irevoire** [meilisearch/arroy#74]
We need to do an investigation

**Comment by curquiza** [comment]
https://github.com/meilisearch/meilisearch/issues/4588

**Comment by irevoire** [comment]
The logs that caused the panic:
```
updating settings
adding document
index 0: removing item 0
index 0: adding item 0 with vector [0.0, 0.0, 0.0]
index 0: building
deleting embedding
index 0: removing item 0
index 1: removing item 0
doing a search
```

**Comment by irevoire** [comment]
The bug happens when you forget to `.build()` a writer and drop it instead.
When you create a reader from this index, later on, it panics. 
It should return a user error instead.
